// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_TMOMENTSARTICLEADDRQ_MOMENTSPACK_H_
#define FLATBUFFERS_GENERATED_TMOMENTSARTICLEADDRQ_MOMENTSPACK_H_

#include "flatbuffers.h"

#include "common_generated.h"

namespace momentspack {

struct T_MOMENTS_ARTICLE_ADD_RQ;

struct T_MOMENTS_ARTICLE_ADD_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_ARTICLE_ID = 6,
    VT_USER_ID = 8,
    VT_USER_NICKNAME = 10,
    VT_TITLE = 12,
    VT_CONTENT_TYPE = 14,
    VT_CONTENT = 16,
    VT_PRIV_TYPE = 18,
    VT_WHITE_LIST = 20,
    VT_BLACK_LIST = 22,
    VT_CREATE_TIME = 24
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  uint64_t article_id() const { return GetField<uint64_t>(VT_ARTICLE_ID, 0); }
  uint64_t user_id() const { return GetField<uint64_t>(VT_USER_ID, 0); }
  const flatbuffers::String *user_nickname() const { return GetPointer<const flatbuffers::String *>(VT_USER_NICKNAME); }
  const flatbuffers::String *title() const { return GetPointer<const flatbuffers::String *>(VT_TITLE); }
  int32_t content_type() const { return GetField<int32_t>(VT_CONTENT_TYPE, 0); }
  const flatbuffers::String *content() const { return GetPointer<const flatbuffers::String *>(VT_CONTENT); }
  int32_t priv_type() const { return GetField<int32_t>(VT_PRIV_TYPE, 0); }
  const flatbuffers::String *white_list() const { return GetPointer<const flatbuffers::String *>(VT_WHITE_LIST); }
  const flatbuffers::String *black_list() const { return GetPointer<const flatbuffers::String *>(VT_BLACK_LIST); }
  uint64_t create_time() const { return GetField<uint64_t>(VT_CREATE_TIME, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_ARTICLE_ID) &&
           VerifyField<uint64_t>(verifier, VT_USER_ID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_USER_NICKNAME) &&
           verifier.Verify(user_nickname()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_TITLE) &&
           verifier.Verify(title()) &&
           VerifyField<int32_t>(verifier, VT_CONTENT_TYPE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_CONTENT) &&
           verifier.Verify(content()) &&
           VerifyField<int32_t>(verifier, VT_PRIV_TYPE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_WHITE_LIST) &&
           verifier.Verify(white_list()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_BLACK_LIST) &&
           verifier.Verify(black_list()) &&
           VerifyField<uint64_t>(verifier, VT_CREATE_TIME) &&
           verifier.EndTable();
  }
};

struct T_MOMENTS_ARTICLE_ADD_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_MOMENTS_ARTICLE_ADD_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_article_id(uint64_t article_id) { fbb_.AddElement<uint64_t>(T_MOMENTS_ARTICLE_ADD_RQ::VT_ARTICLE_ID, article_id, 0); }
  void add_user_id(uint64_t user_id) { fbb_.AddElement<uint64_t>(T_MOMENTS_ARTICLE_ADD_RQ::VT_USER_ID, user_id, 0); }
  void add_user_nickname(flatbuffers::Offset<flatbuffers::String> user_nickname) { fbb_.AddOffset(T_MOMENTS_ARTICLE_ADD_RQ::VT_USER_NICKNAME, user_nickname); }
  void add_title(flatbuffers::Offset<flatbuffers::String> title) { fbb_.AddOffset(T_MOMENTS_ARTICLE_ADD_RQ::VT_TITLE, title); }
  void add_content_type(int32_t content_type) { fbb_.AddElement<int32_t>(T_MOMENTS_ARTICLE_ADD_RQ::VT_CONTENT_TYPE, content_type, 0); }
  void add_content(flatbuffers::Offset<flatbuffers::String> content) { fbb_.AddOffset(T_MOMENTS_ARTICLE_ADD_RQ::VT_CONTENT, content); }
  void add_priv_type(int32_t priv_type) { fbb_.AddElement<int32_t>(T_MOMENTS_ARTICLE_ADD_RQ::VT_PRIV_TYPE, priv_type, 0); }
  void add_white_list(flatbuffers::Offset<flatbuffers::String> white_list) { fbb_.AddOffset(T_MOMENTS_ARTICLE_ADD_RQ::VT_WHITE_LIST, white_list); }
  void add_black_list(flatbuffers::Offset<flatbuffers::String> black_list) { fbb_.AddOffset(T_MOMENTS_ARTICLE_ADD_RQ::VT_BLACK_LIST, black_list); }
  void add_create_time(uint64_t create_time) { fbb_.AddElement<uint64_t>(T_MOMENTS_ARTICLE_ADD_RQ::VT_CREATE_TIME, create_time, 0); }
  T_MOMENTS_ARTICLE_ADD_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_MOMENTS_ARTICLE_ADD_RQBuilder &operator=(const T_MOMENTS_ARTICLE_ADD_RQBuilder &);
  flatbuffers::Offset<T_MOMENTS_ARTICLE_ADD_RQ> Finish() {
    auto o = flatbuffers::Offset<T_MOMENTS_ARTICLE_ADD_RQ>(fbb_.EndTable(start_, 11));
    return o;
  }
};

inline flatbuffers::Offset<T_MOMENTS_ARTICLE_ADD_RQ> CreateT_MOMENTS_ARTICLE_ADD_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    uint64_t article_id = 0,
    uint64_t user_id = 0,
    flatbuffers::Offset<flatbuffers::String> user_nickname = 0,
    flatbuffers::Offset<flatbuffers::String> title = 0,
    int32_t content_type = 0,
    flatbuffers::Offset<flatbuffers::String> content = 0,
    int32_t priv_type = 0,
    flatbuffers::Offset<flatbuffers::String> white_list = 0,
    flatbuffers::Offset<flatbuffers::String> black_list = 0,
    uint64_t create_time = 0) {
  T_MOMENTS_ARTICLE_ADD_RQBuilder builder_(_fbb);
  builder_.add_create_time(create_time);
  builder_.add_user_id(user_id);
  builder_.add_article_id(article_id);
  builder_.add_black_list(black_list);
  builder_.add_white_list(white_list);
  builder_.add_priv_type(priv_type);
  builder_.add_content(content);
  builder_.add_content_type(content_type);
  builder_.add_title(title);
  builder_.add_user_nickname(user_nickname);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_MOMENTS_ARTICLE_ADD_RQ> CreateT_MOMENTS_ARTICLE_ADD_RQDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    uint64_t article_id = 0,
    uint64_t user_id = 0,
    const char *user_nickname = nullptr,
    const char *title = nullptr,
    int32_t content_type = 0,
    const char *content = nullptr,
    int32_t priv_type = 0,
    const char *white_list = nullptr,
    const char *black_list = nullptr,
    uint64_t create_time = 0) {
  return CreateT_MOMENTS_ARTICLE_ADD_RQ(_fbb, s_rq_head, article_id, user_id, user_nickname ? _fbb.CreateString(user_nickname) : 0, title ? _fbb.CreateString(title) : 0, content_type, content ? _fbb.CreateString(content) : 0, priv_type, white_list ? _fbb.CreateString(white_list) : 0, black_list ? _fbb.CreateString(black_list) : 0, create_time);
}

inline const momentspack::T_MOMENTS_ARTICLE_ADD_RQ *GetT_MOMENTS_ARTICLE_ADD_RQ(const void *buf) {
  return flatbuffers::GetRoot<momentspack::T_MOMENTS_ARTICLE_ADD_RQ>(buf);
}

inline bool VerifyT_MOMENTS_ARTICLE_ADD_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<momentspack::T_MOMENTS_ARTICLE_ADD_RQ>(nullptr);
}

inline void FinishT_MOMENTS_ARTICLE_ADD_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<momentspack::T_MOMENTS_ARTICLE_ADD_RQ> root) {
  fbb.Finish(root);
}

}  // namespace momentspack

#endif  // FLATBUFFERS_GENERATED_TMOMENTSARTICLEADDRQ_MOMENTSPACK_H_
