// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_TMOMENTSCOMMENTADDRS_MOMENTSPACK_H_
#define FLATBUFFERS_GENERATED_TMOMENTSCOMMENTADDRS_MOMENTSPACK_H_

#include "flatbuffers.h"

#include "common_generated.h"
#include "t_moments_common_generated.h"

namespace momentspack {

struct T_MOMENTS_COMMENT_ADD_RS;

struct T_MOMENTS_COMMENT_ADD_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_COMMENT = 6
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  const momentspack::T_MOMENTS_COMMENT_DTO *comment() const { return GetPointer<const momentspack::T_MOMENTS_COMMENT_DTO *>(VT_COMMENT); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_COMMENT) &&
           verifier.VerifyTable(comment()) &&
           verifier.EndTable();
  }
};

struct T_MOMENTS_COMMENT_ADD_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_MOMENTS_COMMENT_ADD_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_comment(flatbuffers::Offset<momentspack::T_MOMENTS_COMMENT_DTO> comment) { fbb_.AddOffset(T_MOMENTS_COMMENT_ADD_RS::VT_COMMENT, comment); }
  T_MOMENTS_COMMENT_ADD_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_MOMENTS_COMMENT_ADD_RSBuilder &operator=(const T_MOMENTS_COMMENT_ADD_RSBuilder &);
  flatbuffers::Offset<T_MOMENTS_COMMENT_ADD_RS> Finish() {
    auto o = flatbuffers::Offset<T_MOMENTS_COMMENT_ADD_RS>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_MOMENTS_COMMENT_ADD_RS> CreateT_MOMENTS_COMMENT_ADD_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    flatbuffers::Offset<momentspack::T_MOMENTS_COMMENT_DTO> comment = 0) {
  T_MOMENTS_COMMENT_ADD_RSBuilder builder_(_fbb);
  builder_.add_comment(comment);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline const momentspack::T_MOMENTS_COMMENT_ADD_RS *GetT_MOMENTS_COMMENT_ADD_RS(const void *buf) {
  return flatbuffers::GetRoot<momentspack::T_MOMENTS_COMMENT_ADD_RS>(buf);
}

inline bool VerifyT_MOMENTS_COMMENT_ADD_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<momentspack::T_MOMENTS_COMMENT_ADD_RS>(nullptr);
}

inline void FinishT_MOMENTS_COMMENT_ADD_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<momentspack::T_MOMENTS_COMMENT_ADD_RS> root) {
  fbb.Finish(root);
}

}  // namespace momentspack

#endif  // FLATBUFFERS_GENERATED_TMOMENTSCOMMENTADDRS_MOMENTSPACK_H_
