// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_TMOMENTSCOMMENTADDRQ_MOMENTSPACK_H_
#define FLATBUFFERS_GENERATED_TMOMENTSCOMMENTADDRQ_MOMENTSPACK_H_

#include "flatbuffers.h"

#include "common_generated.h"
#include "t_moments_common_generated.h"

namespace momentspack {

struct T_MOMENTS_COMMENT_ADD_RQ;

struct T_MOMENTS_COMMENT_ADD_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_COMMENT = 6
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  const momentspack::T_MOMENTS_COMMENT_DTO *comment() const { return GetPointer<const momentspack::T_MOMENTS_COMMENT_DTO *>(VT_COMMENT); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_COMMENT) &&
           verifier.VerifyTable(comment()) &&
           verifier.EndTable();
  }
};

struct T_MOMENTS_COMMENT_ADD_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_MOMENTS_COMMENT_ADD_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_comment(flatbuffers::Offset<momentspack::T_MOMENTS_COMMENT_DTO> comment) { fbb_.AddOffset(T_MOMENTS_COMMENT_ADD_RQ::VT_COMMENT, comment); }
  T_MOMENTS_COMMENT_ADD_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_MOMENTS_COMMENT_ADD_RQBuilder &operator=(const T_MOMENTS_COMMENT_ADD_RQBuilder &);
  flatbuffers::Offset<T_MOMENTS_COMMENT_ADD_RQ> Finish() {
    auto o = flatbuffers::Offset<T_MOMENTS_COMMENT_ADD_RQ>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_MOMENTS_COMMENT_ADD_RQ> CreateT_MOMENTS_COMMENT_ADD_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    flatbuffers::Offset<momentspack::T_MOMENTS_COMMENT_DTO> comment = 0) {
  T_MOMENTS_COMMENT_ADD_RQBuilder builder_(_fbb);
  builder_.add_comment(comment);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline const momentspack::T_MOMENTS_COMMENT_ADD_RQ *GetT_MOMENTS_COMMENT_ADD_RQ(const void *buf) {
  return flatbuffers::GetRoot<momentspack::T_MOMENTS_COMMENT_ADD_RQ>(buf);
}

inline bool VerifyT_MOMENTS_COMMENT_ADD_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<momentspack::T_MOMENTS_COMMENT_ADD_RQ>(nullptr);
}

inline void FinishT_MOMENTS_COMMENT_ADD_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<momentspack::T_MOMENTS_COMMENT_ADD_RQ> root) {
  fbb.Finish(root);
}

}  // namespace momentspack

#endif  // FLATBUFFERS_GENERATED_TMOMENTSCOMMENTADDRQ_MOMENTSPACK_H_
