// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_TMOMENTSQUERYBYIDSRS_MOMENTSPACK_H_
#define FLATBUFFERS_GENERATED_TMOMENTSQUERYBYIDSRS_MOMENTSPACK_H_

#include "flatbuffers.h"

#include "common_generated.h"
#include "t_moments_common_generated.h"

namespace momentspack {

struct T_MOMENTS_FULL_INFO_DTO;

struct T_MOMENTS_QUERY_BY_IDS_RS;

struct T_MOMENTS_FULL_INFO_DTO FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ARTICLE = 4,
    VT_COMMENTS = 6
  };
  const momentspack::T_MOMENTS_ARTICLE_DTO *article() const { return GetPointer<const momentspack::T_MOMENTS_ARTICLE_DTO *>(VT_ARTICLE); }
  const flatbuffers::Vector<flatbuffers::Offset<momentspack::T_MOMENTS_COMMENT_DTO>> *comments() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<momentspack::T_MOMENTS_COMMENT_DTO>> *>(VT_COMMENTS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_ARTICLE) &&
           verifier.VerifyTable(article()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_COMMENTS) &&
           verifier.Verify(comments()) &&
           verifier.VerifyVectorOfTables(comments()) &&
           verifier.EndTable();
  }
};

struct T_MOMENTS_FULL_INFO_DTOBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_article(flatbuffers::Offset<momentspack::T_MOMENTS_ARTICLE_DTO> article) { fbb_.AddOffset(T_MOMENTS_FULL_INFO_DTO::VT_ARTICLE, article); }
  void add_comments(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<momentspack::T_MOMENTS_COMMENT_DTO>>> comments) { fbb_.AddOffset(T_MOMENTS_FULL_INFO_DTO::VT_COMMENTS, comments); }
  T_MOMENTS_FULL_INFO_DTOBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_MOMENTS_FULL_INFO_DTOBuilder &operator=(const T_MOMENTS_FULL_INFO_DTOBuilder &);
  flatbuffers::Offset<T_MOMENTS_FULL_INFO_DTO> Finish() {
    auto o = flatbuffers::Offset<T_MOMENTS_FULL_INFO_DTO>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_MOMENTS_FULL_INFO_DTO> CreateT_MOMENTS_FULL_INFO_DTO(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<momentspack::T_MOMENTS_ARTICLE_DTO> article = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<momentspack::T_MOMENTS_COMMENT_DTO>>> comments = 0) {
  T_MOMENTS_FULL_INFO_DTOBuilder builder_(_fbb);
  builder_.add_comments(comments);
  builder_.add_article(article);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_MOMENTS_FULL_INFO_DTO> CreateT_MOMENTS_FULL_INFO_DTODirect(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<momentspack::T_MOMENTS_ARTICLE_DTO> article = 0,
    const std::vector<flatbuffers::Offset<momentspack::T_MOMENTS_COMMENT_DTO>> *comments = nullptr) {
  return CreateT_MOMENTS_FULL_INFO_DTO(_fbb, article, comments ? _fbb.CreateVector<flatbuffers::Offset<momentspack::T_MOMENTS_COMMENT_DTO>>(*comments) : 0);
}

struct T_MOMENTS_QUERY_BY_IDS_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_USER_ID = 6,
    VT_FULL_INFOS = 8
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  uint64_t user_id() const { return GetField<uint64_t>(VT_USER_ID, 0); }
  const flatbuffers::Vector<flatbuffers::Offset<T_MOMENTS_FULL_INFO_DTO>> *full_infos() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<T_MOMENTS_FULL_INFO_DTO>> *>(VT_FULL_INFOS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_USER_ID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_FULL_INFOS) &&
           verifier.Verify(full_infos()) &&
           verifier.VerifyVectorOfTables(full_infos()) &&
           verifier.EndTable();
  }
};

struct T_MOMENTS_QUERY_BY_IDS_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_MOMENTS_QUERY_BY_IDS_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_user_id(uint64_t user_id) { fbb_.AddElement<uint64_t>(T_MOMENTS_QUERY_BY_IDS_RS::VT_USER_ID, user_id, 0); }
  void add_full_infos(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<T_MOMENTS_FULL_INFO_DTO>>> full_infos) { fbb_.AddOffset(T_MOMENTS_QUERY_BY_IDS_RS::VT_FULL_INFOS, full_infos); }
  T_MOMENTS_QUERY_BY_IDS_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_MOMENTS_QUERY_BY_IDS_RSBuilder &operator=(const T_MOMENTS_QUERY_BY_IDS_RSBuilder &);
  flatbuffers::Offset<T_MOMENTS_QUERY_BY_IDS_RS> Finish() {
    auto o = flatbuffers::Offset<T_MOMENTS_QUERY_BY_IDS_RS>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<T_MOMENTS_QUERY_BY_IDS_RS> CreateT_MOMENTS_QUERY_BY_IDS_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t user_id = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<T_MOMENTS_FULL_INFO_DTO>>> full_infos = 0) {
  T_MOMENTS_QUERY_BY_IDS_RSBuilder builder_(_fbb);
  builder_.add_user_id(user_id);
  builder_.add_full_infos(full_infos);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_MOMENTS_QUERY_BY_IDS_RS> CreateT_MOMENTS_QUERY_BY_IDS_RSDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    uint64_t user_id = 0,
    const std::vector<flatbuffers::Offset<T_MOMENTS_FULL_INFO_DTO>> *full_infos = nullptr) {
  return CreateT_MOMENTS_QUERY_BY_IDS_RS(_fbb, s_rs_head, user_id, full_infos ? _fbb.CreateVector<flatbuffers::Offset<T_MOMENTS_FULL_INFO_DTO>>(*full_infos) : 0);
}

inline const momentspack::T_MOMENTS_QUERY_BY_IDS_RS *GetT_MOMENTS_QUERY_BY_IDS_RS(const void *buf) {
  return flatbuffers::GetRoot<momentspack::T_MOMENTS_QUERY_BY_IDS_RS>(buf);
}

inline bool VerifyT_MOMENTS_QUERY_BY_IDS_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<momentspack::T_MOMENTS_QUERY_BY_IDS_RS>(nullptr);
}

inline void FinishT_MOMENTS_QUERY_BY_IDS_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<momentspack::T_MOMENTS_QUERY_BY_IDS_RS> root) {
  fbb.Finish(root);
}

}  // namespace momentspack

#endif  // FLATBUFFERS_GENERATED_TMOMENTSQUERYBYIDSRS_MOMENTSPACK_H_
