// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_TMOMENTSTIMELINEQUERYRS_MOMENTSPACK_H_
#define FLATBUFFERS_GENERATED_TMOMENTSTIMELINEQUERYRS_MOMENTSPACK_H_

#include "flatbuffers.h"

#include "common_generated.h"
#include "t_moments_common_generated.h"

namespace momentspack {

struct T_MOMENTS_TIMELINE_QUERY_RS;

struct T_MOMENTS_TIMELINE_QUERY_RS FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RS_HEAD = 4,
    VT_TIMELINES = 6
  };
  const commonpack::S_RS_HEAD *s_rs_head() const { return GetStruct<const commonpack::S_RS_HEAD *>(VT_S_RS_HEAD); }
  const flatbuffers::Vector<flatbuffers::Offset<momentspack::T_TIMELINE_DTO>> *timelines() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<momentspack::T_TIMELINE_DTO>> *>(VT_TIMELINES); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RS_HEAD>(verifier, VT_S_RS_HEAD) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_TIMELINES) &&
           verifier.Verify(timelines()) &&
           verifier.VerifyVectorOfTables(timelines()) &&
           verifier.EndTable();
  }
};

struct T_MOMENTS_TIMELINE_QUERY_RSBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rs_head(const commonpack::S_RS_HEAD *s_rs_head) { fbb_.AddStruct(T_MOMENTS_TIMELINE_QUERY_RS::VT_S_RS_HEAD, s_rs_head); }
  void add_timelines(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<momentspack::T_TIMELINE_DTO>>> timelines) { fbb_.AddOffset(T_MOMENTS_TIMELINE_QUERY_RS::VT_TIMELINES, timelines); }
  T_MOMENTS_TIMELINE_QUERY_RSBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_MOMENTS_TIMELINE_QUERY_RSBuilder &operator=(const T_MOMENTS_TIMELINE_QUERY_RSBuilder &);
  flatbuffers::Offset<T_MOMENTS_TIMELINE_QUERY_RS> Finish() {
    auto o = flatbuffers::Offset<T_MOMENTS_TIMELINE_QUERY_RS>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_MOMENTS_TIMELINE_QUERY_RS> CreateT_MOMENTS_TIMELINE_QUERY_RS(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<momentspack::T_TIMELINE_DTO>>> timelines = 0) {
  T_MOMENTS_TIMELINE_QUERY_RSBuilder builder_(_fbb);
  builder_.add_timelines(timelines);
  builder_.add_s_rs_head(s_rs_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_MOMENTS_TIMELINE_QUERY_RS> CreateT_MOMENTS_TIMELINE_QUERY_RSDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RS_HEAD *s_rs_head = 0,
    const std::vector<flatbuffers::Offset<momentspack::T_TIMELINE_DTO>> *timelines = nullptr) {
  return CreateT_MOMENTS_TIMELINE_QUERY_RS(_fbb, s_rs_head, timelines ? _fbb.CreateVector<flatbuffers::Offset<momentspack::T_TIMELINE_DTO>>(*timelines) : 0);
}

inline const momentspack::T_MOMENTS_TIMELINE_QUERY_RS *GetT_MOMENTS_TIMELINE_QUERY_RS(const void *buf) {
  return flatbuffers::GetRoot<momentspack::T_MOMENTS_TIMELINE_QUERY_RS>(buf);
}

inline bool VerifyT_MOMENTS_TIMELINE_QUERY_RSBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<momentspack::T_MOMENTS_TIMELINE_QUERY_RS>(nullptr);
}

inline void FinishT_MOMENTS_TIMELINE_QUERY_RSBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<momentspack::T_MOMENTS_TIMELINE_QUERY_RS> root) {
  fbb.Finish(root);
}

}  // namespace momentspack

#endif  // FLATBUFFERS_GENERATED_TMOMENTSTIMELINEQUERYRS_MOMENTSPACK_H_
