// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_TMOMENTSQUERYBYIDSRQ_MOMENTSPACK_H_
#define FLATBUFFERS_GENERATED_TMOMENTSQUERYBYIDSRQ_MOMENTSPACK_H_

#include "flatbuffers.h"

#include "common_generated.h"
#include "t_moments_common_generated.h"

namespace momentspack {

struct T_MOMENTS_QUERY_BY_IDS_RQ;

struct T_MOMENTS_QUERY_BY_IDS_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_USER_ID = 6,
    VT_TIMELINES = 8
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  uint64_t user_id() const { return GetField<uint64_t>(VT_USER_ID, 0); }
  const flatbuffers::Vector<flatbuffers::Offset<momentspack::T_TIMELINE_DTO>> *timelines() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<momentspack::T_TIMELINE_DTO>> *>(VT_TIMELINES); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_USER_ID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_TIMELINES) &&
           verifier.Verify(timelines()) &&
           verifier.VerifyVectorOfTables(timelines()) &&
           verifier.EndTable();
  }
};

struct T_MOMENTS_QUERY_BY_IDS_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_MOMENTS_QUERY_BY_IDS_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_user_id(uint64_t user_id) { fbb_.AddElement<uint64_t>(T_MOMENTS_QUERY_BY_IDS_RQ::VT_USER_ID, user_id, 0); }
  void add_timelines(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<momentspack::T_TIMELINE_DTO>>> timelines) { fbb_.AddOffset(T_MOMENTS_QUERY_BY_IDS_RQ::VT_TIMELINES, timelines); }
  T_MOMENTS_QUERY_BY_IDS_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_MOMENTS_QUERY_BY_IDS_RQBuilder &operator=(const T_MOMENTS_QUERY_BY_IDS_RQBuilder &);
  flatbuffers::Offset<T_MOMENTS_QUERY_BY_IDS_RQ> Finish() {
    auto o = flatbuffers::Offset<T_MOMENTS_QUERY_BY_IDS_RQ>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<T_MOMENTS_QUERY_BY_IDS_RQ> CreateT_MOMENTS_QUERY_BY_IDS_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    uint64_t user_id = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<momentspack::T_TIMELINE_DTO>>> timelines = 0) {
  T_MOMENTS_QUERY_BY_IDS_RQBuilder builder_(_fbb);
  builder_.add_user_id(user_id);
  builder_.add_timelines(timelines);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_MOMENTS_QUERY_BY_IDS_RQ> CreateT_MOMENTS_QUERY_BY_IDS_RQDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    uint64_t user_id = 0,
    const std::vector<flatbuffers::Offset<momentspack::T_TIMELINE_DTO>> *timelines = nullptr) {
  return CreateT_MOMENTS_QUERY_BY_IDS_RQ(_fbb, s_rq_head, user_id, timelines ? _fbb.CreateVector<flatbuffers::Offset<momentspack::T_TIMELINE_DTO>>(*timelines) : 0);
}

inline const momentspack::T_MOMENTS_QUERY_BY_IDS_RQ *GetT_MOMENTS_QUERY_BY_IDS_RQ(const void *buf) {
  return flatbuffers::GetRoot<momentspack::T_MOMENTS_QUERY_BY_IDS_RQ>(buf);
}

inline bool VerifyT_MOMENTS_QUERY_BY_IDS_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<momentspack::T_MOMENTS_QUERY_BY_IDS_RQ>(nullptr);
}

inline void FinishT_MOMENTS_QUERY_BY_IDS_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<momentspack::T_MOMENTS_QUERY_BY_IDS_RQ> root) {
  fbb.Finish(root);
}

}  // namespace momentspack

#endif  // FLATBUFFERS_GENERATED_TMOMENTSQUERYBYIDSRQ_MOMENTSPACK_H_
