// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_TMOMENTSSETTINGBLACKNOTCARELISTMODIFYRQ_MOMENTSPACK_H_
#define FLATBUFFERS_GENERATED_TMOMENTSSETTINGBLACKNOTCARELISTMODIFYRQ_MOMENTSPACK_H_

#include "flatbuffers.h"

#include "common_generated.h"

namespace momentspack {

struct T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ;

struct T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_USER_ID = 6,
    VT_LIST_TYPE = 8,
    VT_LIST = 10
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  uint64_t user_id() const { return GetField<uint64_t>(VT_USER_ID, 0); }
  int8_t list_type() const { return GetField<int8_t>(VT_LIST_TYPE, 0); }
  const flatbuffers::String *list() const { return GetPointer<const flatbuffers::String *>(VT_LIST); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<uint64_t>(verifier, VT_USER_ID) &&
           VerifyField<int8_t>(verifier, VT_LIST_TYPE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_LIST) &&
           verifier.Verify(list()) &&
           verifier.EndTable();
  }
};

struct T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_user_id(uint64_t user_id) { fbb_.AddElement<uint64_t>(T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ::VT_USER_ID, user_id, 0); }
  void add_list_type(int8_t list_type) { fbb_.AddElement<int8_t>(T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ::VT_LIST_TYPE, list_type, 0); }
  void add_list(flatbuffers::Offset<flatbuffers::String> list) { fbb_.AddOffset(T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ::VT_LIST, list); }
  T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQBuilder &operator=(const T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQBuilder &);
  flatbuffers::Offset<T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ> Finish() {
    auto o = flatbuffers::Offset<T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ>(fbb_.EndTable(start_, 4));
    return o;
  }
};

inline flatbuffers::Offset<T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ> CreateT_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    uint64_t user_id = 0,
    int8_t list_type = 0,
    flatbuffers::Offset<flatbuffers::String> list = 0) {
  T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQBuilder builder_(_fbb);
  builder_.add_user_id(user_id);
  builder_.add_list(list);
  builder_.add_s_rq_head(s_rq_head);
  builder_.add_list_type(list_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ> CreateT_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    uint64_t user_id = 0,
    int8_t list_type = 0,
    const char *list = nullptr) {
  return CreateT_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ(_fbb, s_rq_head, user_id, list_type, list ? _fbb.CreateString(list) : 0);
}

inline const momentspack::T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ *GetT_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ(const void *buf) {
  return flatbuffers::GetRoot<momentspack::T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ>(buf);
}

inline bool VerifyT_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<momentspack::T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ>(nullptr);
}

inline void FinishT_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<momentspack::T_MOMENTS_SETTING_BLACKNOTCARELIST_MODIFY_RQ> root) {
  fbb.Finish(root);
}

}  // namespace momentspack

#endif  // FLATBUFFERS_GENERATED_TMOMENTSSETTINGBLACKNOTCARELISTMODIFYRQ_MOMENTSPACK_H_
