// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_FBCLIENTOFFCIALGETUNREADCNTRQ_OFFCIALPACK_H_
#define FLATBUFFERS_GENERATED_FBCLIENTOFFCIALGETUNREADCNTRQ_OFFCIALPACK_H_

#include "flatbuffers.h"

#include "common_generated.h"

namespace offcialpack {

struct T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ;

struct T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_S_RQ_HEAD = 4,
    VT_LIST_B_ID = 6
  };
  const commonpack::S_RQ_HEAD *s_rq_head() const { return GetStruct<const commonpack::S_RQ_HEAD *>(VT_S_RQ_HEAD); }
  const flatbuffers::Vector<uint64_t> *list_b_id() const { return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_LIST_B_ID); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<commonpack::S_RQ_HEAD>(verifier, VT_S_RQ_HEAD) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_LIST_B_ID) &&
           verifier.Verify(list_b_id()) &&
           verifier.EndTable();
  }
};

struct T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_s_rq_head(const commonpack::S_RQ_HEAD *s_rq_head) { fbb_.AddStruct(T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ::VT_S_RQ_HEAD, s_rq_head); }
  void add_list_b_id(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> list_b_id) { fbb_.AddOffset(T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ::VT_LIST_B_ID, list_b_id); }
  T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQBuilder &operator=(const T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQBuilder &);
  flatbuffers::Offset<T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ> Finish() {
    auto o = flatbuffers::Offset<T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ> CreateT_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> list_b_id = 0) {
  T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQBuilder builder_(_fbb);
  builder_.add_list_b_id(list_b_id);
  builder_.add_s_rq_head(s_rq_head);
  return builder_.Finish();
}

inline flatbuffers::Offset<T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ> CreateT_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const commonpack::S_RQ_HEAD *s_rq_head = 0,
    const std::vector<uint64_t> *list_b_id = nullptr) {
  return CreateT_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ(_fbb, s_rq_head, list_b_id ? _fbb.CreateVector<uint64_t>(*list_b_id) : 0);
}

inline const offcialpack::T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ *GetT_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ(const void *buf) {
  return flatbuffers::GetRoot<offcialpack::T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ>(buf);
}

inline bool VerifyT_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<offcialpack::T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ>(nullptr);
}

inline void FinishT_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<offcialpack::T_CLIENT_OFFCIAL_GET_UNREAD_CNT_RQ> root) {
  fbb.Finish(root);
}

}  // namespace offcialpack

#endif  // FLATBUFFERS_GENERATED_FBCLIENTOFFCIALGETUNREADCNTRQ_OFFCIALPACK_H_
